### ISSUE TITLE
Subscribing does not work, merge_fields sent as array

### ISSUE THREAD

**Issue by kdambekalns** [bwaidelich/Wwwision.Neos.MailChimp#11]
When subscribing this is sent:

    {"email_address":"foo@bar.invalid","status":"pending","merge_fields":[]}

which results in a 400 response, saying

> The resource submitted could not be validated. For field-specific details, see the 'errors' array.

Which is:

    {"field":"merge_fields","message":"Schema describes object, array found instead"}

This is the finisher config:

    finishers:
        -
            identifier: 'Wwwision.Neos.MailChimp:MailChimpSubscriptionFinisher'
            options:
                listId: 'xxxxxxx'

Note there are no `additionalOptions` set. As soon as some are set, an object is sent along and everything works as expected.

**Comment by bwaidelich** [comment]
Thanks for reporting, I'll look into this. Can you share which version you are referring to?

**Comment by bwaidelich** [comment]
@kdambekalns I hope you were referring to the latest release – this one should fix the issue https://github.com/bwaidelich/Wwwision.Neos.MailChimp/releases/tag/4.0.1  thanks for reporting

**Comment by kdambekalns** [comment]
The latest, yep. Will report back if it's _not_ fixed… thanks!
