### ISSUE TITLE
Translate email unique validation

### ISSUE THREAD

**Issue by krsriq** [bwaidelich/Wwwision.Neos.MailChimp#15]
How can I translate the email validation string here:
https://github.com/bwaidelich/Wwwision.Neos.MailChimp/blob/71069ae43a4d0a0e9fe7d074de591fabdf534e31/Classes/Wwwision/Neos/MailChimp/Validation/Validator/UniqueSubscriptionValidator.php#L41

**Comment by bwaidelich** [comment]
Sorry for the late reaction. Translation of validation messages is not special to this package - it is done like with any other form translation, see https://flow-form-framework.readthedocs.io/en/latest/translating-forms.html
