### ISSUE TITLE
Class 'mailchimp' not found

### ISSUE THREAD

**Issue by christian-fries** [bwaidelich/Wwwision.Neos.MailChimp#6]
I installed the plugin on my Neos 1.2.8 installation but it doesn't work, I get this error: 
> Fatal error: Class 'Mailchimp' not found in Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Wwwision_Neos_MailChimp_Domain_Service_MailChimpService.php on line 30

I added the plugin in my distribution package in composer.json in the require section:
> "wwwision/neos-mailchimp": "dev-master"

I flushed caches in both development and production context but it doesn't work. Any ideas?

**Comment by bwaidelich** [comment]
Hi,
after adding the dependency you got to install the dependencies using composer (see https://getcomposer.org/).
Usually a simple `composer install` is enough

**Comment by bwaidelich** [comment]
@christian-fries did that work for you?

**Comment by christian-fries** [comment]
Thanks for your message! I already fetched/installed the dependencies with `composer update` but that didn't help. Does the order of dependencies matter (in this case)? 
The mailchimp source is in `/Packages/Libraries/mailchimp/mailchimp/src` and in autoload_namespaces.php is an entry with 
> 'Mailchimp' => array($vendorDir . '/mailchimp/mailchimp/src'),

so as far as I know it should be loaded. 

Do you have any other ideas?

**Comment by bwaidelich** [comment]
@christian-fries Thanks for the update. There seems to be issues with some 3rd party composer packages and the Flow autoloader. Try `composer install -o` to optimize the autoloader classmap.
I also updated the README file
