### ISSUE TITLE
Exception because of form builder config

### ISSUE THREAD

**Issue by Sebobo** [bwaidelich/Wwwision.Neos.MailChimp#7]
I'm currently adapting the package for Flow 3 / Neos 2. 
There was not much to do except this: https://github.com/Sebobo/Wwwision.Neos.MailChimp/commit/b5801bebb1bc0a989ecb16b49639f95c6dcd30e9

But I get an error with the Settings:

    Uncaught exception #1325697085 in line 348 of /somepath/app/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/TYPO3_Form_Core_Model_FormDefinition.php: The options "formBuilder" were not allowed (allowed were: "rendererClassName, renderingOptions, finishers")

Does the form builder config require an additional dependency?

**Comment by bwaidelich** [comment]
@Sebobo sorry, I somehow missed this one.. I'm looking into it now

**Comment by bwaidelich** [comment]
I don't see how that error could be related, but https://github.com/bwaidelich/Wwwision.Neos.MailChimp/releases/tag/2.0.0 works for me with Neos master

**Comment by bwaidelich** [comment]
nevermind, I can reproduce the exception now with latest master.. Need to look into that

**Comment by Sebobo** [comment]
Awesome thx
